### ISSUE TITLE
divide function throw an error

### ISSUE THREAD

**Issue by brobeckero** [gbrian/grafana-timelion-datasource#3] opened 2017-09-14 12:24 UTC
hello,

I got an issue when trying to use the divide function:

here is the formula which is working on kibana that i'm trying to use : 

.es(index=stok).divide(.es(index=mmsc-logs))

and I got the following error :

{
  "title": "SyntaxError: {\"type\":\"incompleteFunction\",\"function\":\"divide\",\"location\":{\"min\":16,\"max\":23},\"text\":\".divide\"}",
  "message": "SyntaxError: {\"type\":\"incompleteFunction\",\"function\":\"divide\",\"location\":{\"min\":16,\"max\":23},\"text\":\".divide\"}",
  "stack": "SyntaxError: {\"type\":\"incompleteFunction\",\"function\":\"divide\",\"location\":{\"min\":16,\"max\":23},\"text\":\".divide\"}\n    at peg$buildException (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:363:14)\n    at error (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:221:13)\n    at peg$c28 (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:120:11)\n    at peg$parsefunction (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:836:18)\n    at peg$parsechain (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:934:14)\n    at peg$parseseries_type (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:630:18)\n    at peg$parseseries (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:645:12)\n    at peg$parsestart (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:376:12)\n    at Object.peg$parse [as parse] (eval at compile (/usr/share/kibana/node_modules/pegjs/lib/compiler.js:1:0), <anonymous>:1390:18)\n    at /usr/share/kibana/src/core_plugins/timelion/server/handlers/lib/parse_sheet.js:13:21\n    at arrayMap (/usr/share/kibana/node_modules/lodash/index.js:1406:25)\n    at Function.map (/usr/share/kibana/node_modules/lodash/index.js:6710:14)\n    at parseSheet (/usr/share/kibana/src/core_plugins/timelion/server/handlers/lib/parse_sheet.js:11:12)\n    at Object.processRequest (/usr/share/kibana/src/core_plugins/timelion/server/handlers/chain_runner.js:189:13)\n    at /usr/share/kibana/src/core_plugins/timelion/server/routes/run.js:30:51\n    at undefined.next (native)"
}

I think the issue is that a re writing rule is inserting a coma just before the second .es call :

![image](https://user-images.githubusercontent.com/29971245/30429557-fc19fcd4-9968-11e7-883f-df9f7a78b90e.png)

thx before hand for your help

BR.

**Comment by gbrian** [comment] 2017-09-14 15:20
Hi @brobeckero ,

Yep, it looks like i'm doing something weird with the ".es(", I'll try to reproduce
`var targets = _.map(target.split(".es(").slice(1), part => ".es(" + part);`

**Comment by brobeckero** [comment] 2017-09-15 06:47
hello,

replaced your line with this one and it did pass my test.

var targets = _.map(target.split(/^\.es\(|,\s*.es\(/).slice(1), function
(part)

not sure about regression though

2017-09-14 19:20 GMT+04:00 Gustavo Brian <notifications@github.com>:

**Comment by gbrian** [comment] 2017-09-15 08:08
Ho @brobeckero ,

That works really fine
![image](https://user-images.githubusercontent.com/767180/30472668-c34afa80-99fd-11e7-82fa-be4c928f3962.png)

👍  fixing
Thanks

**Comment by gbrian** [comment] 2017-09-15 08:35
@brobeckero ,

Now fixed and pushed. Thanks a lot for your help 👍 

![image](https://user-images.githubusercontent.com/767180/30473682-7dd0b8d8-9a01-11e7-90a4-91339694fdf9.png)

**Closed by gbrian** 2017-09-15 08:35 UTC
