### ISSUE TITLE
strange behavior on scale_interval / time-interval

### ISSUE THREAD

**Issue by afeshti** [gbrian/grafana-timelion-datasource#15] opened 2018-11-14 08:40 UTC
Hello, first of all thank you for this project.

I have a strange behavior on calculating uniq ip hitting my network. To calculate this I use cardinality metric on a scale of 1 second. The query, directly on kibana-timelion is this one:

```
.es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 8.8.8.8', 
metric=cardinality:netflow.ipv4_src_addr).scale_interval(1s)
```

So, if we check the value they say something like 100-200 per second in the last 15 minutes:

![image](https://user-images.githubusercontent.com/9715870/48467863-7bca0200-e7ea-11e8-8ac1-0076e9f920c3.png)

If we change timescale, ad ask the same thing for the last hour, in kibana we still have the same value:

![image](https://user-images.githubusercontent.com/9715870/48467928-b338ae80-e7ea-11e8-8617-8edff58ed768.png)

So the value are mediated in time and we get a mediated value per second.

If I try to do the same thing on grafana (rel. 5.3.1) I get an error:

last 15 minutes:

![image](https://user-images.githubusercontent.com/9715870/48468106-3fe36c80-e7eb-11e8-841a-4a949d435c5b.png)

error on last 1 hour:

![image](https://user-images.githubusercontent.com/9715870/48468176-73be9200-e7eb-11e8-9032-d156ad221405.png)

Seems like grafana is not mediating the data on query. 
Checking the query generated by kibana-timelion, we can se that asking last 15 minutes we get:

```
{"sheet":[".es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 8.8.8.8', metric=cardinality:netflow.ipv4_src_addr).scale_interval(1s)"],"time":{"from":"now-15m","to":"now","mode":"quick","interval":"auto","timezone":"Europe/Berlin"}}`
```

asking last hour we get:
```
{"sheet":[".es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 8.8.8.8', metric=cardinality:netflow.ipv4_src_addr).scale_interval(1s)"],"time":{"from":"now-1h","to":"now","mode":"quick","interval":"auto","timezone":"Europe/Berlin"}}`
```

So, the **scale_interval** stay at **1s**, and the **"interval"** in **"time"** section stay **"auto"**.

Checking the same in the grafana-timelione side we get:

last 15 min:
```
{"sheet":[".es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 8.8.8.8', metric=cardinality:netflow.ipv4_src_addr)"],"time":{"from":"2018-11-14T07:50:55Z","interval":"1s","mode":"absolute","timezone":"GMT","to":"2018-11-14T08:05:55Z"}}`
```

last hour:
```
{"sheet":[".es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 8.8.8.8', metric=cardinality:netflow.ipv4_src_addr)"],"time":{"from":"2018-11-14T07:07:18Z","interval":"1s","mode":"absolute","timezone":"GMT","to":"2018-11-14T08:07:18Z"}}`
```

So, via grafana-timelion, the **scale_interval(1s)** is lost  and the value of scale_interval has been passed to **time interval** parameter. 

----------

One last thing on scale_interval, if we double the query to check to different destination:
```
.es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 8.8.8.8', 
metric=cardinality:netflow.ipv4_src_addr).scale_interval(1s),.es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 7.7.7.7', 
metric=cardinality:netflow.ipv4_src_addr).scale_interval(1s)
```

![image](https://user-images.githubusercontent.com/9715870/48470060-b898f780-e7f0-11e8-811c-0ef5ac8dee07.png)

the scale interval in the POST vs timelion is passed only in the second metric:
```
{"sheet":[".es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 8.8.8.8', metric=cardinality:netflow.ipv4_src_addr),.es(index='netflow-example.com-*', timefield='netflow.last_switched', q='netflow.ipv4_dst_addr: 7.7.7.7', metric=cardinality:netflow.ipv4_src_addr).scale_interval(1s)"],"time":{"from":"2018-11-14T08:29:30Z","interval":"1s","mode":"absolute","timezone":"GMT","to":"2018-11-14T08:34:30Z"}}
```

Versions: grafana: 5.3.1, kibana: 6.4.0, and last version of timelion-datasource.

Thank you,
AF

**Comment by gbrian** [comment] 2018-11-14 11:53
Hi @afeshti ,
Thanks for the detailed information. I'll read carefully and try to reproduce- you almost gave me the lines of code 😄 thanks -.
Back to you asap.

**Comment by gbrian** [comment] 2018-11-15 06:34
Hi @afeshti 
I've been testing this behavior and trying to remember why I implemented the `scale_interval` this way.
Here are my findings:

**Same error in Timelion and Grafana for a 1 hour data at 1s interval**
![image](https://user-images.githubusercontent.com/767180/48533748-f3a93280-e8a5-11e8-986e-4723756a70b5.png)
 
Scale is defined by elasticsearch `interval` value and not by Timelion's `scale_interval` function, so using the `scale_interval` function has not impact- at least on my current version 5.3.0-

**Elastic `auto` Timelion `1m` for a 15m window**
![image](https://user-images.githubusercontent.com/767180/48534268-de350800-e8a7-11e8-9ff7-067a7d149034.png)

**Changing Timelion to `10m` does not affect**
![image](https://user-images.githubusercontent.com/767180/48534361-25bb9400-e8a8-11e8-948c-ceabe996be26.png)

Grafana implementation takes this value from Timelion's and uses it on the `Interval` setting to elasticsearch then `strips` the function as it not really needed.
Aside effect if you have multiple queries, you can define multiple scales.
![image](https://user-images.githubusercontent.com/767180/48534439-73380100-e8a8-11e8-95bf-07b99bed7a69.png)

Currently behavior seems to be the same for me but I've not reproduced your case as Timelion complains for a `1h` of data at a `1s` scale- interval set by kibana-

**Comment by gbrian** [comment] 2018-11-15 06:37
I'll do some tests with latest versio using https://demo.elastic.co/app/timelion and update you asap.

**Comment by gbrian** [comment] 2018-11-15 06:50
@afeshti ,
Gotcha, was able to reproduce and realiced my error. I'll fix asap.

**Comment by afeshti** [comment] 2018-11-15 07:08
@gbrian thank you, let me know if I can help with tests or something.

**Comment by gbrian** [comment] 2018-11-16 19:05
Hi @afeshti , 
Hope this is fixed now! 💪 
Thanks for the catch, please close the issue if it works fine for you as well.

**Comment by afeshti** [comment] 2018-11-17 08:48
perfect, all ok, thank you!

**Closed** 2018-11-17 08:48 UTC
